[tools]
"aqua:tealdeer-rs/tealdeer" = "latest"
bat = "latest"
fd = "latest"
delta = "latest"
lazygit = "latest"
zoxide = "latest"
eza = "latest"
yq = "latest"
fzf = "latest"
direnv = "latest"
starship = "latest"
helix = "latest"
ruff = "latest"
